packages/agent/src/parsers.ts
packages/app/features/scan/ScanScreen.tsx
packages/app/hooks/useCredentialDataHandler.tsx

Signed-off-by: Karim Stekelenburg <karim@animo.id>

fix: qr scanner now reactivates and shows err msg

---

apps/expo/app/_layout.tsx

According to expo docs we need to import it from the router package. Maybe this helps with the white screen being showed instead of the splash screen

fix: import splash screen from router

---

packages/agent/src/display.ts
packages/app/components/CredentialAttributes.tsx
packages/app/features/wallet/WalletScreen.tsx
packages/app/utils/formatCredentialSubject.ts
packages/ui/src/table/TableRow.tsx

feat: support images in credentials

---

packages/agent/package.json
packages/agent/src/parsers.ts
yarn.lock

feat: Added support for url query inside the didcomm deeplink

---

packages/agent/src/parsers.ts

It was working in testing because there is also a url property inside the object that you get back from the parser which is the raw url. So it was a accidental success. With the rename to oobUrl it didn't work anymore because the property is not available in the root object which is also correct. All the queries are inside the query object.
This is tested and it's working.

fix: OobUrl query fetching

---

packages/agent/src/hooks/useInboxNotifications.ts

Shows the OOB label when there's no connection. The connectionless flow fully works already, except that it shows "Unknown" as the issuer/verifier label

feat: show oob label when no connection

---

packages/agent/src/hooks/index.ts
packages/agent/src/hooks/useAcceptDidCommPresentation.ts
packages/agent/src/hooks/useDidCommCredentialActions.ts
packages/agent/src/hooks/useDidCommPresentationActions.ts
packages/app/features/notifications/DidCommCredentialNotificationScreen.tsx
packages/app/features/notifications/DidCommPresentationNotificationScreen.tsx

Implementation for the decline problem report in the Paradym wallet.

feat: Decline problem report

---

.yarn/patches/@sd-jwt-decode-npm-0.2.1-4ba346c112.patch
package.json
packages/app/utils/formatCredentialSubject.ts
yarn.lock

It's a bit unfortunate, but there's a bug in sd-jwt library when rendering a boolean value of false (and also a bug in our wallet, but that was easy to fix). So for now I patch it, as Credo is in the process of updating SD-jWT implementation

fix: render false boolean

---

apps/expo/package.json
packages/agent/src/didcomm/metadata.ts
packages/agent/src/display.ts
packages/agent/src/hooks/useCredentialForDisplayById.ts
packages/agent/src/hooks/useCredentialsForDisplay.ts
packages/agent/src/hooks/useDidCommCredentialActions.ts
packages/agent/src/invitation/handler.ts
packages/agent/src/openid4vc/metadata.ts

AnonCreds credentials are now stored in W3C format. This makes it easier to deal with, and we don't have to render credential exchange records anymore. However, we do lose all metadata for currently issued AnonCreds credentials as these are in the CredentialExchangeRecord and there's actually a bug in Credo that makes it hard to migrate this.

fix: credentials shown multiple times

---

packages/agent/src/hooks/useDidCommPresentationActions.ts

Made it so it favors the way of combining the credentials in Paradym, after that it will combine them based on the credentialId. And if that isn't available it will still use the groupname. 
So the groupname will be used when the credential is not available in the wallet and the proof request didn't came from Paradym.

feat: Merge anoncreds proof request credentials

---

packages/agent/src/agent.ts

Importing the cheqd module gives errors in the funke app. As we're not using cheqd, I worked around it for now, but I'm not sure how the Paradym wallet does not have this issue?
Maybe it's related to #127 ?  Edit: can't imagine that is the issue. The changes recently to cheqd were minima: https://github.com/openwallet-foundation/credo-ts/pull/1954/files

fix: unhandled promise rejection

---

apps/funke/package.json
apps/funke/src/constants.ts
apps/funke/src/use-cases/ReceivePidUseCase.ts
package.json
packages/agent/src/invitation/handler.ts
pnpm-lock.yaml

chore: check vct scheme to choose hardware/software key

---

apps/easypid/src/app/(app)/credentials/requestedAttributes.tsx
apps/easypid/src/crypto/bPrime.ts
apps/easypid/src/features/activity/FunkeActivityDetailScreen.tsx
apps/easypid/src/features/activity/FunkeActivityScreen.tsx
apps/easypid/src/features/activity/activityRecord.ts
apps/easypid/src/features/onboarding/onboardingContext.tsx
apps/easypid/src/features/onboarding/screens/id-card-requested-attributes.tsx
apps/easypid/src/features/receive/FunkeOpenIdCredentialNotificationScreen.tsx
apps/easypid/src/features/receive/slides/OfferCredentialSlide.tsx
apps/easypid/src/features/share/FunkeOpenIdPresentationNotificationScreen.tsx
apps/easypid/src/features/share/FunkeRequestedAttributesDetailScreen.tsx
apps/easypid/src/features/share/components/RequestedAttributesSection.tsx
apps/easypid/src/features/share/slides/ShareCredentialsSlide.tsx
apps/easypid/src/hooks/usePidCredential.tsx
apps/easypid/src/use-cases/ReceivePidUseCaseBPrimeFlow.ts
apps/easypid/src/use-cases/ReceivePidUseCaseCFlow.ts
apps/easypid/src/use-cases/ReceivePidUseCaseFlow.ts
packages/agent/src/format/formatPresentation.ts
packages/app/src/components/SlideWizard.tsx
packages/ui/src/components/ProgressHeader.tsx
packages/ui/src/content/Icon.tsx

- Activity detail screen improved with support for multiple credentials
- In a presentation request, it will now display the correct attributes coun
- Progress bar is now completed in line with the animation when receiving a credential
- Moved the reason to the top in presentation request screen
- Reverted 'Germany' to 'Bundesdruckerei'
- Minor ui improvements

fix: fixed attributes count and ui improvements

---

packages/secure-store/secure-wallet-key/SecureUnlockProvider.tsx

@TimoGlastra This fixes the unlocking issue, but it might break other things. Any reason why `setCanTryUnlockingUsingBiometrics` before unlocking?

fix: unlocking with face id

---

apps/easypid/src/features/activity/FunkeActivityDetailScreen.tsx
apps/easypid/src/features/share/components/RequestedAttributesSection.tsx
apps/easypid/src/features/wallet/FunkeCredentialDetailScreen.tsx
packages/agent/src/display.ts
packages/app/src/components/BlurBadge.tsx
packages/app/src/components/CardInfoLifecycle.tsx
packages/app/src/components/CardWithAttributes.tsx
packages/app/src/components/FunkeCredentialCard.tsx
packages/ui/src/components/InfoButton.tsx
packages/ui/src/panels/InfoSheet.tsx
packages/ui/src/utils/variants.ts
packages/utils/src/format.ts

- Added states on the credential detail page
- Added expired/revoked badges to credential card
- Added expired/revoked state to be used in the presentation screen when attributes from an expired/revoked card are requested.
Expiry and from date already works, the other states is just UI.

feat: lifecycle states

---

apps/easypid/src/app/(app)/_layout.tsx
apps/easypid/src/app/(app)/pidSetup.tsx
apps/easypid/src/app/authenticate.tsx
apps/easypid/src/features/menu/FunkeMenuScreen.tsx
apps/easypid/src/features/onboarding/onboardingContext.tsx
apps/easypid/src/features/onboarding/screens/id-card-scan.tsx
apps/easypid/src/features/onboarding/screens/id-card-start.tsx
apps/easypid/src/features/pid/FunkePidSetupScreen.tsx
apps/easypid/src/features/pid/PidCardScanSlide.tsx
apps/easypid/src/features/pid/PidEidCardFetchSlide.tsx
apps/easypid/src/features/pid/PidEidCardPinSlide.tsx
apps/easypid/src/features/pid/PidReviewRequestSlide.tsx
apps/easypid/src/features/pid/PidSetupStartSlide.tsx
apps/easypid/src/features/pid/PidWalletPinSlide.tsx
apps/easypid/src/features/wallet/FunkeWalletScreen.tsx
apps/easypid/src/utils/sharedPidSetup.ts
apps/easypid/tamagui.config.ts
packages/app/src/components/CardWithAttributes.tsx
packages/app/src/components/SlideWizard.tsx
packages/ui/src/components/IdCard.tsx

I tried to re-use some screens but i've copied over a lot of the logic because it's hard to understand code and some things just work a bit different if you already have a wallet. So to not make the logic in the onboarding even more unreadable i just did it like this.
TODOs

feat: pid flow in wallet

---

apps/easypid/src/features/pid/FunkePidSetupScreen.tsx
apps/easypid/src/features/pid/PidEidCardFetchSlide.tsx
packages/app/src/components/SlideWizard.tsx

Not an ideal fix, still thinking how we can do it better.
The problem is that because we now do () => <Screen />, it re-renders everytime something changes in the properties passed to that screen. This means that once the state changes after the scan is complete, the screen renders again, and it triggers again. 
I tried fixing it with useMemo but that leads to the same thing.

fix: pid setup fix

---

apps/easypid/src/app/authenticate.tsx
apps/easypid/src/crypto/WalletServiceProviderClient.ts
apps/easypid/src/crypto/error.ts
apps/easypid/src/features/onboarding/screens/data-protection.tsx
apps/easypid/src/features/pid/FunkePidSetupScreen.tsx
apps/easypid/src/features/pid/PidWalletPinSlide.tsx
apps/easypid/src/features/receive/FunkeCredentialNotificationScreen.tsx
apps/easypid/src/features/scan/FunkeQrScannerScreen.tsx
apps/easypid/src/features/share/FunkeOpenIdPresentationNotificationScreen.tsx
apps/easypid/src/features/share/slides/PinSlide.tsx
apps/easypid/src/features/share/slides/ShareCredentialsSlide.tsx
apps/easypid/src/hooks/useCanUseSecureEnclave.ts
packages/agent/src/agent.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix: handle invalid pin when sharing or after onboarding

---

apps/easypid/README.md
apps/easypid/src/app/+native-intent.tsx
apps/easypid/src/features/menu/FunkeSettingsScreen.tsx
apps/easypid/src/features/receive/FunkeCredentialNotificationScreen.tsx
apps/easypid/src/features/receive/slides/AuthCodeFlowSlide.tsx
apps/easypid/src/features/share/FunkeOpenIdPresentationNotificationScreen.tsx
apps/easypid/src/features/share/slides/PinSlide.tsx
apps/easypid/src/hooks/index.ts
apps/easypid/src/hooks/useDevelopmentMode.ts
packages/app/src/components/SlideWizard.tsx

Three features / fixed in one PR 🙈 
- Added a development mode that shows internal error messages for easier debugging by LSPs [commit](https://github.com/animo/paradym-wallet/commit/a1aaf26655456082d15863d6f88edecfecaca598)
- Fixed an issue where the PIN screen would get stuck in a loading state when an incorrect PIN was entered  [commit](https://github.com/animo/paradym-wallet/commit/0f65ef98f5f26c3afc0968e4f848bf538a86cfd7)
- Fixed an issue with redirect based auth flow if the authorization flow left the in-app browser (e.g. when requiring authentication using the native AusweisApp with the eID card) [commit](https://github.com/animo/paradym-wallet/commit/eb333b81fe5662cc2f010e1ee9bbdc83a7e19aa3)

some fixes and updates

---

apps/easypid/src/features/proximity/mdocProximity.ts
package.json
pnpm-lock.yaml
pnpm-workspace.yaml

This pr does three things:
- update credo to released fork of Credo. This will make dependency management easier. You can also exactly see which commit will be used as each release is created as a tag, e.g. https://github.com/animo/credo-ts/tree/v0.5.14-alpha-20250128050818
- Allow mdoc with oid4vp without JARM (requirement for potential)
- support multiple mdocs in a proximity flow (@berendsliedrecht )

feat: support multi-document mdoc device response

---

patches/@animo-id__credo-ts-core.patch
pnpm-lock.yaml

Interop with mattr verifier from https://tools.mattrlabs.com/mdoc-online-presentation
Patch can be removed once https://github.com/openwallet-foundation/credo-ts/pull/2204 is merged

fix: mattr verifier interop

---

apps/easypid/src/app/(app)/federation.tsx
apps/easypid/src/features/activity/activityRecord.ts
apps/easypid/src/features/didcomm/ConnectionSlides.tsx
apps/easypid/src/features/didcomm/CredentialSlides.tsx
apps/easypid/src/features/didcomm/DidCommNotificationScreen.tsx
apps/easypid/src/features/receive/FunkeOpenIdCredentialNotificationScreen.tsx
apps/easypid/src/features/receive/slides/InteractionErrorSlide.tsx
apps/easypid/src/features/receive/slides/VerifyPartySlide.tsx
apps/easypid/src/features/share/FunkeMdocOfflineSharingScreen.tsx
apps/easypid/src/features/share/FunkeOpenIdPresentationNotificationScreen.tsx
apps/easypid/src/features/share/FunkePresentationNotificationScreen.tsx
apps/easypid/src/features/wallet/FunkeFederationDetailScreen.tsx
packages/agent/src/hooks/useDidCommConnectionActions.ts

Some additions to #324, to correctly handle errors, and also reuse the error screen for all flows.

refactor: handle connection flow and errors

---

apps/easypid/src/app/+native-intent.tsx
apps/easypid/src/app/authenticate.tsx
packages/app/src/components/TextBackButton.tsx

replaces #337 
- Request authentication when a deeplink is being used (same fix as in #337)
- Fixes the issue when the app is longer in the background that the deeplink still works, comes with the side effect that when the app is not so long in the background that it needs to re-auth, which I think is okay. Mainly, because re-authenticating within an such a fraud sensitive platform is not a bad thing. Most people, if not all, use biometrics and make the authentication extremely fast.
I could not test it with the Ausweis flow as I do not have a card and I could not find the website anymore. I think the deeplink working has a priority over the ausweis flow for now.

fix: redirect works when app is longer in background
