apps/expo/package.json, package.json, packages/agent/src/agent.ts, yarn.lock
I've also tested it with a credential issuance from Paradym
=> feat: Added mainnet to cheqd

packages/app/components/InboxNotificationRowCard.tsx, packages/app/features/notifications/NotificationInboxScreen.tsx
=> fix: notification card title layout

packages/app/features/notifications/components/CredentialNotificationScreen.tsx, packages/app/features/notifications/components/PresentationNotificationScreen.tsx, packages/ui/src/panels/ToastContainer.tsx
- List properties correctly in proof request
- Make credential notification min height full screen
- Improve clickbox of close icon on toast
=> fix: small ui fixes

apps/expo/package.json
Updates version so we can make a new release
=> chore: update version to 1.2.3

apps/expo/package.json
Always forget to update the version. ....
=> chore: update version to 1.2.4

packages/app/src/hooks/useTransparentNavigationBar.tsx, packages/app/src/utils/DeeplinkHandler.tsx
=> fix: test full flows

.github/workflows/continuous-deployment.yaml
=> chore: change funke -> ausweis for CD

apps/ausweis/app.config.js
=> chore: add EAS id

packages/agent/package.json, packages/agent/src/index.ts, pnpm-lock.yaml
=> fix: add text encoder polyfill

apps/easypid/src/app/(app)/_layout.tsx, apps/easypid/src/app/(app)/pinConfirmation.tsx, apps/easypid/src/crypto/bPrime.ts, apps/easypid/src/features/wallet/FunkeOpenIdPresentationNotificationScreen.tsx, apps/easypid/src/features/wallet/FunkePidConfirmationScreen.tsx, apps/easypid/src/hooks/usePidCredential.tsx, apps/easypid/src/use-cases/ReceivePidUseCaseBPrimeFlow.ts
=> feat: pin confirmation

apps/easypid/src/features/onboarding/onboardingContext.tsx, apps/easypid/src/use-cases/ReceivePidUseCaseBPrimeFlow.ts
=> feat: do not reuse pin for B' flow

apps/easypid/src/features/wallet/FunkePresentationNotificationScreen.tsx, apps/easypid/src/hooks/usePidCredential.tsx, packages/agent/src/display.ts, packages/agent/src/format/formatPresentation.ts, packages/agent/src/hooks/useDidCommPresentationActions.ts, packages/ui/src/components/ActivityRowItem.tsx, packages/ui/src/components/IdCard.tsx
=> fix: ui bugs

apps/easypid/src/app/(app)/_layout.tsx, apps/easypid/src/app/(app)/pinLocked.tsx, apps/easypid/src/features/onboarding/onboardingContext.tsx, apps/easypid/src/features/wallet/FunkeOpenIdPresentationNotificationScreen.tsx, apps/easypid/src/features/wallet/FunkePidConfirmationScreen.tsx, apps/easypid/src/features/wallet/FunkePinLockedScreen.tsx, packages/ui/src/content/IllustrationContainer.tsx
- Jan will add a variant to the illustration container to give it a red color with the `variant="danger"`
=> feat: pin locked screen

apps/easypid/src/app/authenticate.tsx, apps/easypid/src/features/activity/activityRecord.ts, apps/easypid/src/features/wallet/FunkeOpenIdPresentationNotificationScreen.tsx, apps/easypid/src/features/wallet/FunkePresentationNotificationScreen.tsx
stores activity payload and fixes bug with activity not updating.
=> feat: activity payload

apps/easypid/src/agent/initialize.ts, apps/easypid/src/app/authenticate.tsx, apps/easypid/src/features/onboarding/hasFinishedOnboarding.ts, apps/easypid/src/features/onboarding/onboardingContext.tsx, apps/easypid/src/utils/resetWallet.ts, packages/secure-store/secure-wallet-key/SecureUnlockProvider.tsx, packages/secure-store/secure-wallet-key/secureWalletKey.ts
Signed-off-by: Timo Glastra <timo@animo.id>
=> fix: wallet reset

apps/easypid/package.json, apps/easypid/src/features/wallet/FunkePresentationNotificationScreen.tsx, apps/paradym/app/_layout.tsx, apps/paradym/package.json, apps/storybook/package.json, packages/agent/src/agent.ts, packages/agent/src/invitation/handler.ts, packages/agent/src/invitation/index.ts, packages/app/src/components/DualResponseButtons.tsx, packages/app/src/components/InboxIcon.tsx, packages/app/src/components/InboxNotificationRowCard.tsx, packages/app/src/components/NoContentInbox.tsx, packages/app/src/features/credentials/CredentialDetailScreen.tsx, packages/app/src/features/notifications/NotificationInboxScreen.tsx, packages/app/src/features/notifications/components/CredentialNotificationScreen.tsx, packages/app/src/features/notifications/components/PresentationNotificationScreen.tsx, packages/ui/src/components/NfcScannerModalAndroid.tsx, packages/ui/src/config/tamagui.config.ts, packages/ui/src/content/Icon.tsx, packages/ui/src/panels/Sheet.tsx, pnpm-lock.yaml
- Added header to Inbox screen
- Switched all sheets to Tamagui
- Added delete credential UI 
~~Still need to do the delete logic, but not sure how that works with all the credential types. Maybe you can point me in the right direction (or create a hook i can use :))? @TimoGlastra~~ It works!
https://github.com/user-attachments/assets/17aaeb42-dc3d-483e-961a-70e929294905
=> feat: delete credential and ui improvements

apps/easypid/app.config.js, apps/easypid/src/features/onboarding/screens/id-card-pin.tsx, apps/easypid/src/features/onboarding/screens/id-card-start.tsx, apps/easypid/src/features/onboarding/screens/introduction-steps.tsx, apps/easypid/src/features/onboarding/screens/welcome.tsx, apps/easypid/src/features/wallet/FunkeWalletScreen.tsx, packages/ui/src/base/Page.tsx, packages/ui/src/base/Stacks.tsx, packages/ui/src/components/IdCard.tsx, packages/ui/src/content/AnimatedNfcScan.tsx, packages/ui/src/content/Spinner.tsx
As small iPhones do not have a safe area the content was against the bottom edge. I've added a very small safe area which fixes this. I've also moved the eID pin input to the card itself instead of below it.
=> fix: small device improvements

apps/paradym/package.json, package.json
Supersedes #180 but for main branch. It's now merged into main of credo
Removed the source in the custom funke branch, so we don't need the postinstall anymore
=> feat: multi vp support

apps/easypid/app.config.js, apps/easypid/package.json, pnpm-lock.yaml
=> feat(mdoc): added mdoc-data-transfer dependency

apps/easypid/babel.config.js, apps/easypid/package.json, apps/easypid/src/features/proximity/mdocProximity.ts, package.json, pnpm-lock.yaml
=> fix(mdoc): fix dependency versions and return requested items

package.json, pnpm-lock.yaml
=> fix(mdoc): update proximity library

apps/easypid/src/agent/initialize.ts
=> feat: set fallback URL for the WSP

apps/easypid/src/features/menu/FunkeAboutScreen.tsx, apps/easypid/src/features/menu/FunkeMenuScreen.tsx, packages/ui/src/components/InfoButton.tsx, packages/ui/src/content/Icon.tsx
Added text to about screen, and link to privacy policy. Also added temporary mailto link for the feedback item.
=> feat: about screen and privacy policy

apps/easypid/src/features/onboarding/onboardingContext.tsx, package.json, pnpm-lock.yaml
Dependent on https://github.com/animo/expo-secure-environment/pull/18
=> feat: default to cloud hsm

apps/easypid/src/app/(app)/_layout.tsx, apps/easypid/src/app/+native-intent.tsx, apps/easypid/src/app/[...unmatched].tsx, apps/easypid/src/app/authenticate.tsx, packages/agent/src/invitation/parsers.ts, packages/app/src/features/notifications/DidCommCredentialNotificationScreen.tsx, packages/app/src/features/notifications/DidCommNotificationScreen.tsx, packages/app/src/features/notifications/DidCommPresentationNotificationScreen.tsx, packages/app/src/features/notifications/OpenIdCredentialNotificationScreen.tsx, packages/app/src/features/notifications/OpenIdPresentationNotificationScreen.tsx, packages/app/src/hooks/usePushToWallet.tsx, packages/app/src/utils/DeeplinkHandler.tsx
I think it now finally works correctly when the wallet is closed and open using native intents and redirects
=> fix: deeplinks and redirection

apps/easypid/README.md, apps/easypid/src/app/+native-intent.tsx
Signed-off-by: Timo Glastra <timo@animo.id>
=> fix: deeplinking if wallet is open ios

apps/easypid/README.md, apps/easypid/src/features/onboarding/onboardingContext.tsx, apps/easypid/src/features/onboarding/screens/id-card-requested-attributes.tsx, apps/easypid/src/features/pid/FunkePidSetupScreen.tsx, apps/easypid/src/use-cases/ReceivePidUseCaseCFlow.ts, apps/easypid/src/use-cases/ReceivePidUseCaseFlow.ts
Signed-off-by: Timo Glastra <timo@animo.id>
=> fix: issue with ausweis sdk when setting up pid later

apps/paradym/app.config.js
- Resolved  issue with pnpm prebuild command
=> fix: resolve issue with pnpm prebuild command

package.json, packages/agent/src/invitation/shareProof.ts, patches/@animo-id__credo-ts-core.patch, patches/@animo-id__credo-ts-openid4vc.patch, pnpm-lock.yaml, pnpm-workspace.yaml
All the patches needed for french playground
=> fix: patches for french playground

apps/easypid/src/features/proximity/mdocProximity.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: update mdoc sdk

apps/easypid/src/features/menu/FunkeMenuScreen.tsx, packages/ui/src/base/Headings.tsx, packages/ui/src/content/HeaderContainer.tsx, packages/ui/src/content/Icon.tsx, packages/ui/src/content/IconContainer.tsx, packages/ui/src/panels/MessageBox.tsx
=> feat: new menu

apps/easypid/src/features/share/FunkeMdocOfflineSharingScreen.tsx, apps/easypid/src/features/share/FunkeOfflineSharingScreen.tsx, apps/easypid/src/features/share/components/RequestedAttributesSection.tsx, apps/easypid/src/features/wallet/FunkeOfflineQrScreen.tsx, package.json, packages/agent/src/format/mdocRequest.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(proximity): allow for mulitple credential sharing

apps/easypid/src/features/proximity/mdocProximity.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix: update credo

apps/easypid/src/features/onboarding/screens/data-protection.tsx
=> fix: do not popup when secure enclave is not available

apps/easypid/src/features/share/FunkeMdocOfflineSharingScreen.tsx
=> chore: add dev toasts

packages/agent/src/invitation/handler.ts, packages/agent/src/invitation/index.ts, packages/app/src/components/CardWithAttributes.tsx
it would not show the last attribute if odd number of attributes
also removes two unused methods
=> fix: bug with the displayed attributesg

apps/easypid/src/features/proximity/mdocProximity.ts, package.json, packages/agent/src/agent.ts, patches/@animo-id__mdoc.patch, pnpm-lock.yaml, pnpm-workspace.yaml
- Make sure we can reply to an mdoc request when we do not have all attributes and we just send w/e we do have.
=> fix: all fixes for the utrecht interop event

apps/easypid/package.json, apps/easypid/src/app/(app)/(home)/scan.tsx, apps/easypid/src/app/+native-intent.tsx, apps/easypid/src/features/menu/FunkeAboutScreen.tsx, apps/easypid/src/features/share/components/RequestedAttributesSection.tsx, apps/easypid/src/features/wallet/FunkeCredentialDetailScreen.tsx, apps/easypid/src/features/wallet/components/CustomCredentialAttributes.tsx, apps/easypid/src/use-cases/ReceivePidUseCaseCFlow.ts, packages/agent/src/agent.ts, packages/agent/src/hooks/useCredentialByCategory.ts, packages/agent/src/providers/AgentProvider.tsx, packages/app/src/components/DeleteCredentialSheet.tsx, packages/ui/src/base/Headings.tsx, packages/ui/src/table/TableRow.tsx, pnpm-lock.yaml
- Allow PID delete in dev mode
- Minor MDL custom view improvements
=> fix: minor improvs

apps/easypid/src/app/(app)/(home)/scan.tsx, apps/easypid/src/features/share/FunkeRequestedAttributesDetailScreen.tsx, packages/app/src/components/CredentialAttributes.tsx, packages/app/src/hooks/useCredentialDataHandler.tsx, packages/app/src/utils/formatSubject.ts, packages/scanner/src/Scanner.tsx
Some minor fixes related to my recent attributes changes.
=> feat: small atr changes

apps/easypid/src/features/activity/activityRecord.ts, apps/easypid/src/features/didcomm/useDidCommCredentialNotificationSlides.tsx, apps/easypid/src/features/didcomm/useDidCommPresentationNotificationSlides.tsx, apps/easypid/src/features/receive/FunkeOpenIdCredentialNotificationScreen.tsx, apps/easypid/src/features/receive/slides/OfferCredentialSlide.tsx, packages/agent/src/hooks/useDidCommCredentialActions.ts, packages/agent/src/hooks/useDidCommPresentationActions.ts, packages/app/src/components/CardWithAttributes.tsx, packages/app/src/components/FunkeCredentialCard.tsx, packages/app/src/features/scan/ScanScreen.tsx, packages/app/src/utils/formatSubject.ts, packages/scanner/src/Scanner.tsx
- Added activity for new cards
- Added verifier screens for both didcomm issuance and verification
- Predicates are now shown in the requested attributes detail screen
- Purpose will be shown (once merged in Paradym)
=> feat: didcomm ui improvements

pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: update secure env on iOS

apps/easypid/src/app/+native-intent.tsx, apps/easypid/src/features/receive/FunkeOpenIdCredentialNotificationScreen.tsx, apps/easypid/src/features/share/FunkeOpenIdPresentationNotificationScreen.tsx, packages/agent/src/invitation/fetchInvitation.ts, packages/agent/src/invitation/handler.ts, packages/agent/src/invitation/parsers.ts, packages/agent/src/openid4vc/credentialBindingResolver.ts, packages/agent/src/openid4vc/displayMetadata.ts, packages/app/src/features/notifications/OpenIdCredentialNotificationScreen.tsx, packages/app/src/features/notifications/OpenIdPresentationNotificationScreen.tsx, packages/app/src/hooks/useCredentialDataHandler.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
Also fixes some issues with urls for oid4vp.
=> feat: support oid4vci draft 15

apps/easypid/src/features/proximity/mdocProximity.ts, apps/easypid/src/features/wallet/FunkeOfflineQrScreen.tsx, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: update mdoc library

apps/easypid/package.json, apps/easypid/src/features/share/DcApiSharingScreen.tsx, packages/agent/src/display.ts, packages/agent/src/openid4vc/credentialBindingResolver.ts, packages/agent/src/openid4vc/dcApi.ts, packages/agent/src/openid4vc/registerDcApi.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> feat: dc api ui improvements

apps/easypid/src/features/wallet/FunkeTrustDetailScreen.tsx, packages/agent/src/utils/trust.ts
=> fix: added did trust mechanism

apps/easypid/src/features/wallet/FunkeOfflineQrScreen.tsx
Should address FUN-506
It's a bit fiddly because iOS automatically asks for permissions by itself when you try using Bluetooth. However, the approach seems to work just fine.
=> feat: ask for bluetooth access if not given

apps/easypid/package.json
Prepare for a new release of the Paradym Wallet
=> chore: update version

apps/easypid/src/locales/fi/messages.json
Updates the finnish translations based on the reviewed file by Findynet
cc @samuelmr (thanks!)
=> chore: update finnish translations
